baseURL = "https://blog.sriramsv.com/"
languageCode = 'en-us'
title = "Sriram's Blog"
theme = 'PaperMod'
googleAnalytics = "G-QD65HWQW7M"

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[params]
  author = ['Sriram']

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

  [params.profileMode]
    enabled = true
    title = "Sriram"
    subtitle = "Automating life, one day at a time."
    imageUrl = "images/profile.svg"
    imageTitle = "Sriram"
    imageWidth = 150
    imageHeight = 150
    buttons = [
      { name = "Posts", url = "/posts/" },
    ]

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/sriramsv"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sriramsv/"

  [[params.socialIcons]]
    name = "rss"
    url = "index.xml"

[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'Search'
    url = '/search/'
    weight = 2
